### ISSUE TITLE
US1 - Show List with all Animals

### ISSUE THREAD

**Issue by DErdmann1** [DErdmann1/Pfoten-Portal#1]
## Value proposition

As a user
I want a list that shows me all available animals
so that I know which animals I can adopt

## Description

![Image](https://user-images.githubusercontent.com/125928500/251233374-1e363439-a88c-454c-8082-3ae343d3d1cb.png)

## Acceptance criteria

- [ ] The list of animals is displayed in alphabetical order.
- [ ] The list contains a picture of each animal.
- [ ] The list contains the name, age, and current location of each animal.

## Tasks

- [ ] Create a data.js file for the list of animals.
- [ ] Write a function to retrieve the list of animals from data.js.
- [ ] Write a function to sort the list of animals in alphabetical order.

**Comment by VolkerJacobsen** [comment]
Love your project. Userstory looks good but do you really need 4 different functions to retrieve the different infos from your data.js?

**Comment by DErdmann1** [comment]
Thanks for your comment @VolkerJacobsen :) True, I think it was a bit too detailed.

**Comment by VolkerJacobsen** [comment]
Looks great
