### ISSUE TITLE
US7 - Homepage / Navigation

### ISSUE THREAD

**Issue by DErdmann1** [DErdmann1/Pfoten-Portal#10]
## Value proposition

As a user
I want to have three squares on the homepage representing the categories of dogs, cats, and small animals, 
so that I can easily navigate to the category of my choice by clicking on the corresponding square.

## Description

![Image](https://user-images.githubusercontent.com/125928500/252989419-48906ac2-998b-4537-bcd0-d929dac513b9.png)

## Acceptance criteria

- [ ] The homepage has three squares representing the categories of dogs, cats, and small animals.
- [ ] Clicking on a square takes the user to the corresponding category page.

## Tasks

- [ ] Create a new Branch.
- [ ] Add three squares to the homepage representing the categories of dogs, cats, and small animals.
- [ ] Implement the function to navigate to the corresponding category page when a square is clicked.

**Comment by CorneliusMoe** [comment]
Looking good!🐹
