### ISSUE TITLE
US8 - Search function

### ISSUE THREAD

**Issue by DErdmann1** [DErdmann1/Pfoten-Portal#16]
## Value proposition

As a user, I want to search for specific animals by their name,
so that I can easily find the information I need about the animals I'm interested in.

## Description

![Image](https://user-images.githubusercontent.com/125928500/254519308-7fcb6550-7951-46fa-9498-b0ef8b242ac2.png)

## Acceptance criteria

- [ ] A (magnifying glass) icon is visible at the dogs, cats and small animal categorys page
- [ ] When the user enters a search query in the input field and clicks on the magnifying glass icon, the items in the list should be filtered according to the search query.
- [ ] The search function should be case-insensitive, meaning it should return results regardless of whether the search query is in uppercase or lowercase.
- [ ] If the search query does not match any items in the list, a message should be displayed indicating that no results were found.

## Tasks

- [ ] Create a new Branch
- [ ] Implement the search field and magnifying glass icon in the user interface of the Dogs, Cats, and Small Animals categories.
- [ ] Implement the functionality that filters the list items according to the entered search query when the user clicks on the magnifying glass icon.
- [ ] Ensure that the search function is case-insensitive, meaning it should return results regardless of whether the search query is in uppercase or lowercase.
- [ ] Display a message if the search query does not match any items in the list, informing the user that no results were found.

**Comment by CorneliusMoe** [comment]
LGTM 👌
