### ISSUE TITLE
US9 - Add more Content to favorites

### ISSUE THREAD

**Issue by DErdmann1** [DErdmann1/Pfoten-Portal#17]
## Value proposition

As a user, I want to see more information about the animals I have marked as favorites so that I can remember them better and not just see their names.

## Description

![Image](https://user-images.githubusercontent.com/125928500/254903997-6adce816-f616-4fc9-87a3-fbdfcd3b8ab1.png)

## Acceptance criteria

- [ ] On the favorites page, each animal marked as a favorite should display its image, age, gender, breed, and location.
- [ ] Clicking on an animal's image or name should lead the user to its corresponding "More Details" page.
- [ ] The displayed information should be well-organized and easy to read on both desktop and mobile devices.

## Tasks

- [ ] Create a new Branch
- [ ] Modify the favorites page component to retrieve and display the new information for each favorite animal.
- [ ] Create links from the animal's image or name to their respective "More Details" pages.
