### ISSUE TITLE
US2 - Filter function for animal list

### ISSUE THREAD

**Issue by DErdmann1** [DErdmann1/Pfoten-Portal#2]
## Value proposition

As a user
I want to be able to filter the animal list by a certain criterion
so that I only see the animals that meet my requirements.

## Description

![Image](https://user-images.githubusercontent.com/125928500/251418148-06bf0fdf-cf3f-4698-88b3-670ac0964c6c.png)

## Acceptance criteria

- [ ] The animal list can be filtered by different criteria.

## Tasks

- [ ] Create a new Branch
- [ ] Write a function to filter the list of animals by a certain criterion
- [ ] Create a Button to display the filtered animals

**Comment by vaupunkt** [comment]
lgtm :)
