### ISSUE TITLE
US3 - Create "more details" page

### ISSUE THREAD

**Issue by DErdmann1** [DErdmann1/Pfoten-Portal#3]
## Value proposition

As a user
I want to be able to click on the "more details" button
so that I can navigate to a new page and view specific information about the animal I have selected

## Description

![Image](https://user-images.githubusercontent.com/125928500/251469849-c475be72-ec2d-4458-8f69-e02ebdfcc582.png)

![Image](https://user-images.githubusercontent.com/125928500/251469881-83bad164-ed80-476a-bbc5-b915e5b61a5c.png)

## Acceptance criteria

- [ ] A "More Details" button is present and clickable
- [ ] Clicking the button redirects the user to the "More Details" page
- [ ] The "More Details" page displays specific information about the selected animal

## Tasks

- [ ] Create a new Branch
- [ ] Implement the "More Details" button and link it to the corresponding page
- [ ] On the "More Details" page, display the specific information about the selected animal

**Comment by tejue** [comment]
LGTM :)
