### ISSUE TITLE
US4 - Contact form on detail page

### ISSUE THREAD

**Issue by DErdmann1** [DErdmann1/Pfoten-Portal#5]
## Value proposition

As a user
I want to be able to send an email by using the contact form
so that I can express my interest to the actually owner

## Description

![Image](https://user-images.githubusercontent.com/125928500/251511897-00fb6118-7948-4cd8-99e6-bd20b9352fff.png)

## Acceptance criteria

- [ ] The contact form should be displayed on the detail page
- [ ] All fields of the contact form must be required
- [ ] The contact form should have a "Send" or "Submit" button
- [ ] Upon clicking the "Send" or "Submit" button, all form data should be validated and checked

## Tasks

- [ ] Create a new Branch
- [ ] Add the contact form to the detail page and place the required fields for name, email address, subject, and message
- [ ] Implement the validation function to ensure that all fields are filled out and that the email address is in the correct format
- [ ] Implement the email sending function to send the entered data to the owner

**Comment by AliaksandraNovikava** [comment]
Your user story looks great👍
I would suggest only one small adjustment: 
In acceptance criteria you have a "Send" or "Submit" button. Please add this button to your wireframe😀

**Comment by DErdmann1** [comment]
@AliaksandraNovikava thanks for your notice 👍  True, i should add it 😄

**Comment by AliaksandraNovikava** [comment]
LGTM👍
