### ISSUE TITLE
US5 - Bookmark & Footer

### ISSUE THREAD

**Issue by DErdmann1** [DErdmann1/Pfoten-Portal#8]
## Value proposition

As a user
I want to be able to add an animal to my favorites,
so that I can view all of my favorites by clicking on the star icon in the footer.

## Description

![Image](https://user-images.githubusercontent.com/125928500/252927769-6c1c8e14-21b4-41d1-a2ee-7a36644e2e1c.png)

## Acceptance criteria

- [ ] Each animal in the animal list has a small empty star that can be clicked to add the animal to the favorites.
- [ ] When an animal is added to the favorites, the star turns black.
- [ ] There is a footer with an icon to return to the homepage and a star icon to go to the favorites.

## Tasks

- [ ] Create a new Branch.
- [ ] Add an empty star next to each animal in the animal list.
- [ ] Implement the function to add an animal to the favorites when the star is clicked.
- [ ] Change the color of the star to black when an animal is added to the favorites.
- [ ] Add a footer with icons to return to the homepage and to view the favorites.
- [ ] Implement the functions to return to the homepage and view the favorites when the corresponding icons are clicked.
