### ISSUE TITLE
US6 - Header & Logo

### ISSUE THREAD

**Issue by DErdmann1** [DErdmann1/Pfoten-Portal#9]
## Value proposition

As a user
I want to have a fixed header with a Paw-Portal logo,
so that I can always return to the homepage by clicking on the logo.

## Description

![Image](https://user-images.githubusercontent.com/125928500/252971290-6b6b978e-7436-48cb-87ae-cd4f0b7bf504.png)

## Acceptance criteria

- [x] There is a fixed header with a Paw-Portal logo.
- [x] Clicking on the Paw-Portal logo returns the user to the homepage.

## Tasks

- [x] Create a new Branch.
- [x] Add a fixed header with a Paw-Portal logo.
- [x] Implement the function to return to the homepage when the Paw-Portal logo is clicked.

**Comment by CorneliusMoe** [comment]
Thumbs up!
